KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Models/ErrorViewModel.cs
using System;

namespace KhoaLuanTotNghiep_CustomerSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KhoaLuanTotNghiep_CustomerSite.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult SignIn()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, "oidc");
        }

        public new IActionResult SignOut()
        {
            return SignOut(new AuthenticationProperties { RedirectUri = "/" }, "Cookies", "oidc");
        }

        [Authorize]
        public ActionResult MyProfile()
        {
            return View();
        }
    }
}

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Controllers/HomeController.cs
using KhoaLuanTotNghiep_CustomerSite.Models;
using KhoaLuanTotNghiep_CustomerSite.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace KhoaLuanTotNghiep_CustomerSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRealEstateApiClient _realestateApiClient;

        public HomeController(ILogger<HomeController> logger, IRealEstateApiClient productApiClient)
        {
            _logger = logger;
            _realestateApiClient = productApiClient;
        }

        public async Task<IActionResult> Index()
        {
            var results = await _realestateApiClient.GetProducts();
            return View(results);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Controllers/ProductController.cs
using KhoaLuanTotNghiep_CustomerSite.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KhoaLuanTotNghiep_CustomerSite.Controllers
{
    public class ProductController : Controller
    {
        private readonly IRealEstateApiClient _productApiClient;

        public ProductController(IRealEstateApiClient productApiClient)
        {
            _productApiClient = productApiClient;
        }

        [Route("/RealEstate")]
        public async Task<IActionResult> Index()
        {
            var results = await _productApiClient.GetProducts();
            return View(results);
        }

        [Route("/RealEstate/{id}")]
        public async Task<IActionResult> Details(string id)
        {
            var result = await _productApiClient.GetProductById(id);
            return View(result);
        }

        [Route("/Prodcut/category{categoryName}")]
        public async Task<IActionResult> CategoryById(string categoryName)
        {
            var results = await _productApiClient.GetProductByCategory(categoryName);
            return View(results);
        }
    }
}

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Controllers/RateController.cs
using KhoaLuanTotNghiep_CustomerSite.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KhoaLuanTotNghiep_CustomerSite.Controllers
{
    public class RateController : Controller
    {
        private readonly IRealEstateApiClient _realEstateApiClient;

        public RateController(IRealEstateApiClient realEstateApiClient)
        {
            _realEstateApiClient = realEstateApiClient;
        }

        [Authorize]
        public async Task<IActionResult> Voting(string ProductID, int rating)
        {
            string uri_Redirect = Request.Headers["Referer"].ToString();
            var result = await _realEstateApiClient.Rating(ProductID, rating);

            if (result is false)
            {
                return Content("false");
            }
            return Redirect(uri_Redirect);
        }
    }
}

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Controllers/RealEstateController.cs
using KhoaLuanTotNghiep_CustomerSite.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KhoaLuanTotNghiep_CustomerSite.Controllers
{
    public class RealEstateController : Controller
    {
        private readonly IRealEstateApiClient _realestateApiClient;

        public RealEstateController(IRealEstateApiClient productApiClient)
        {
            _realestateApiClient = productApiClient;
        }

        [Route("/RealEstate")]
        public async Task<IActionResult> Index()
        {
            var results = await _realestateApiClient.GetProducts();
            return View(results);
        }

        [Route("/RealEstate/{id}")]
        public async Task<IActionResult> Details(string id)
        {
            var result = await _realestateApiClient.GetProductById(id);
            return View(result);
        }

        [Route("/RealEstate/category{categoryName}")]
        public async Task<IActionResult> CategoryById(string categoryName)
        {
            var results = await _realestateApiClient.GetProductByCategory(categoryName);
            return View(results);
        }
    }
}

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/ViewComponents/CategoryMenuViewComponent.cs
using KhoaLuanTotNghiep_CustomerSite.Service;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace KhoaLuanTotNghiep_CustomerSite.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private readonly ICategoryApiClient _categoryApiClient;

        public CategoryMenuViewComponent(ICategoryApiClient categoryApiClient)
        {
            _categoryApiClient = categoryApiClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryApiClient.GetCategories();

            return View(categories);
        }

    }
}

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<h1>Contact</h1>

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Views/Home/Index.cshtml
@model IList<ShareModel.RealEstateModel>
@section Styles {
<<<<<<< HEAD
    <link rel="stylesheet" href="~/css/home.css" />
=======
    <link rel="stylesheet" href="~/css/Home.css" />
>>>>>>> 463f3093853a650cbe23a8a0ed6670a2c5dd17e3
}


@{ ViewData["Title"] = "Home Page"; }

<div class="container-fluid" style="padding: 0; margin: 0">
    <div class="col height d-flex justify-content-center" id="main">

        <div id="carouselExampleIndicators" class="carousel slide d-flex justify-content-center" data-ride="carousel" style="height: 100%; width: 100%">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>

            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="https://res.cloudinary.com/dusq8k6rj/image/upload/v1633872012/leduyen/w7jqt1cs9b7vi8jjhwo0.jpg" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="https://res.cloudinary.com/dusq8k6rj/image/upload/v1633871979/leduyen/gmhzoxx5cnxtxbtcikz1.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="https://res.cloudinary.com/dusq8k6rj/image/upload/v1633788906/leduyen/wrzqdzhqldo084zkqvbr.jpg" alt="Third slide">
                </div>
            </div>

            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <div id="frm-main" asp-controller="Movies" asp-action="Index" method="get" ">
            <div class="col height d-flex justify-content-center align-items-center" style="width: 100%; height: 100%">
                <div class="dropdown" id="drop-category">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Loại Nhà Dất
                    </button>
                    <span class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="#">Căn hộ, chung cứ</a>
                        <a class="dropdown-item" href="#">Nhà riêng</a>
                        <a class="dropdown-item" href="#">Nhà mặt phố</a>
                        <a class="dropdown-item" href="#">Nhà trọ</a>
                        <a class="dropdown-item" href="#">Văn phòng</a>
                        <a class="dropdown-item" href="#">Cửa hàng</a>
                    </span>
                </div>
                <div class="search">
                    <i class="fa fa-search"></i>
                    <input type="text" class="form-control" placeholder="Have a question? Ask Now">
                    <button class="btn btn-primary d-flex justify-content-center align-items-center">Tìm kiếm</button>
                </div>
            </div>
        </div>
    </div>

    <div class="container" id="title-RealEstate">
        <h2>Bất động sản dành cho bạn</h2>
    </div>
    <div class="card-deck">
        <div class="card" style="width: 0; height: 0; border: none">
            <img class="card-img-top" src="~/images/main.jpg" style="width: 0; height: 0">

        </div>
    </div>
  
        
    <div class="card-deck" id="card-RealEstate">
        @foreach (var product in Model)
        {
        

        <a class="card" asp-action="Details" asp-controller="RealEstate" asp-route-id="@product.RealEstateID">
           
                <img class="card-img-top" src="@product.Image" alt="Card image cap">
                <div class="card-body">
                    <p class="card-title">@product.Title</p>
<<<<<<< HEAD
                    <p class="card-text">@product.Price  <br />    @product.Location</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated 3 mins ago</small>
=======
                    <p class="card-text">@product.Price  -  @product.acreage  <br /><br />    @product.Location</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">@product.CreateTime</small>
>>>>>>> 463f3093853a650cbe23a8a0ed6670a2c5dd17e3
                </div>

        </a>

                }
        </div>
   
    
</div>

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Views/Home/Introduce.cshtml
@{
    ViewData["Title"] = "introduce";
}

<h1>introduce</h1>

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Views/Home/New.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Views/Home/Product.cshtml
@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Views/RealEstate/CategoryById.cshtml
<<<<<<< HEAD
﻿@model IList<ShareModel.RealEstatefromCategory>
=======
﻿@model IEnumerable<ShareModel.RealEstatefromCategory>
@*@model ShareModel.RealEstatefromCategory*@
>>>>>>> 463f3093853a650cbe23a8a0ed6670a2c5dd17e3

@section Styles {
    <link rel="stylesheet" href="~/css/home.css" />
}

@{
    ViewData["Title"] = "introduce";
}

<<<<<<< HEAD

@if (Model.Count() != 0)
{
    <div class="container">
        <h2>Title</h2>
        <hr />

        @foreach (var product in Model)
        {
            <div class="card" style="width: 60%;">
                <div class="row no-gutters">
                    <div class="col-sm-5">
                        <img class="card-img" src="@product.Image" alt="Card image cap">
                    </div>
                    <div class="col-sm-7">
                        <div class="card-body">
                            <p class="card-title">@product.Title</p>
                            <p class="card-text">@product.Price  <br />    @product.Location</p>
                            <a href="#" class="btn btn-primary">View Profile</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}


else
{
    <div class="row">
        <strong>Không có sản phẩm nào!</strong>
    </div>
}
=======
<div class="container">
    @foreach (var name in Model)
    {
        <h2> @name.CategoryName</h2>
        break;
    }


        <hr />
        @if (Model.Count() != 0)
        {
            @foreach (var product in Model)
            {
                <div class="card" style="width: 60%;">
                    <div class="row no-gutters">
                        <div class="col-sm-5">
                            <img class="card-img" src="@product.Image" alt="Card image cap">
                        </div>
                        <div class="col-sm-7">
                            <div class="card-body">
                                <p class="card-title">@product.Title</p>
                                <p class="card-text">@product.Price  <br />    @product.Location</p>
                                <a href="#" class="btn btn-primary">View Profile</a>
                            </div>
                        </div>
                    </div>
                </div>
            }}
        else
        {
            <div class="row">
                <strong>Không có sản phẩm nào!</strong>
            </div>
        }
    </div>


>>>>>>> 463f3093853a650cbe23a8a0ed6670a2c5dd17e3

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Views/RealEstate/Details.cshtml
@model ShareModel.RealEstateModel
@using Microsoft.AspNetCore.Http
<div class="p-5 border rounded">
    <div class="form-group row ">
        <div class="col-6" style="text-align: center;">
            <img src="@Model.Image" alt="New york" style="width:450px;">
        </div>
        <div class="col-6">

            <div class="product-name" style=" text-shadow: black 2px 3px 4px; color: #FFCC66;">
                <h1>@Model.Title</h1>
            </div>
            <hr />
            <p>
                <span class="item-title">ID:</span>
                <span>
                    <strong>
                        @Model.RealEstateID
                    </strong>
                </span>
            </p>
            <p>
                <span class="item-title">Description: @Model.Description</span>
            </p>
            <p>
                <span class="item-title">Category Name: @Model.CategoryName</span>
            </p>
            <div class="price-box">
                <h3>@Model.Price.ToString().Insert(3, ".") VNĐ</h3>
            </div>
            <div>
                @using (Html.BeginForm("addProductToCart", "Product", FormMethod.Post))
                {
                    <input type="hidden" id="id" name="id" value=@Model.RealEstateID />
                    <input type="hidden" id="qty" name="qty" value=1 />
                    <button id="addCart" name="addCart" type="submit" class="btn btn-primary btn-lg btn-block"><i class="fas fa-shopping-cart"></i> Thêm vào yêu thích</button>}
            </div>
            @*<div class="form-group">
<<<<<<< HEAD
                <input hidden asp-for="@Model.RealEstateID" />
                <a asp-controller="Home" asp-action="Index" class="btn btn-success">Back</a>
            </div>*@
=======
                    <input hidden asp-for="@Model.RealEstateID" />
                    <a asp-controller="Home" asp-action="Index" class="btn btn-success">Back</a>
                </div>*@
>>>>>>> 463f3093853a650cbe23a8a0ed6670a2c5dd17e3
        </div>
    </div>
</div>


@if (User.Identity.IsAuthenticated)
{
@using (Html.BeginForm("Voting", "Rating"))
{
@Html.HiddenFor(x => x.RealEstateID)
                    <span class="rate-area">
                        <h5 class="rate">Rate Product</h5>
                        <input type="submit" id="5-star" name="rating" value="5" />
                        <label for="5-star" title="Amazing">5 stars</label>

                        <input type="submit" id="4-star" name="rating" value="4" />
                        <label for="4-star" title="Good">4 stars</label>

                        <input type="submit" id="3-star" name="rating" value="3" />
                        <label for="3-star" title="Average">3 stars</label>

                        <input type="submit" id="2-star" name="rating" value="2" />
                        <label for="2-star" title="Not Good">2 stars</label>

                        <input type="submit" id="1-star" name="rating" value="1" />
                        <label for="1-star" title="Bad">1 star</label>
                    </span>}}

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IList<ShareModel.CategoryModel>

    <ul class="nav-navbar-nav flex-grow-1">
        @foreach (var category in Model)
        {
        <li class="nav-item" style=" display: inline-block;">
            <a class="nav-link text-dark" asp-controller="RealEstate" asp-action="CategoryById" asp-route-categoryName="@category.CategoryName">@category.CategoryName</a>
        </li>
        }
    </ul>

KhoaLuanTotNghiep/KhoaLuanTotNghiep_CustomerSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <environment names="Development">@RenderSection("Styles", required: false)</environment>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KhoaLuanTotNghiep_CustomerSite</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="~/images/logo.jpeg" style="width: 100px">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @await Component.InvokeAsync("CategoryMenu")
                        </li>
                   
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="center-page" style="margin: -10px">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - KhoaLuanTotNghiep_CustomerSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>